#!/bin/bash
echo  "Select: "
echo  "	1. thispersondoesnotexist.com"
echo  "	2. thisartworkdoesnotexist.com"
echo  "	3. thiscatdoesnotexist.com"
echo  "	4. thishorsedoesnotexist.com"
# echo -n "	https://thischemicaldoesnotexist.com/" ???
read SELECT
if (( SELECT == 1 )); then
	SOURCE="https://thispersondoesnotexist.com/image"
elif (( SELECT == 2 )); then
	SOURCE="https://thisartworkdoesnotexist.com/"
elif (( SELECT == 3 )); then
	SOURCE="https://thiscatdoesnotexist.com/"
else
	SOURCE="https://thishorsedoesnotexist.com/"
fi
echo -n "Enter quantity: "
read CALL
clear
if (( CALL > 0 )); then
	CUTIME=0
	AVG=0
	ITER=0
	TSTART=$(date +%s%N)
	for (( i = 0; i < CALL; i++ )); do
		echo -n "$i. "
		CSTART=$(date +%s%N)
		curl -s -o output/$i $SOURCE
		CEND=$(date +%s%N)
		CTIME=$((($CEND-$CSTART)/1000000))
		CUTIME=$(($CUTIME+$CTIME))
		((ITER++))
		echo "done in $CTIME ms."
		tintrmd=$((($(date +%s%N)-$TSTART)/1000000))
		if (( ITER % 48 == 0)); then
			if (( $tintrmd > 60000 )); then
				echo "execution time - $(($tintrmd/60000)) min. $(($tintrmd%60000/1000)) sec. $(($tintrmd%1000)) ms."
			elif (( $tintrmd > 1000 )); then
				echo "execution time - $(($tintrmd/1000)) sec. $(($tintrmd%1000)) ms."
			else
				echo "execution time - $tintrmd ms."
			fi
		fi
		sleep 1
	done
	TEND=$(date +%s%N)
	TTIME=$((($TEND-$TSTART)/1000000))
	AVG=$(($CUTIME/$ITER))
	echo "------------------"
	if (( $CUTIME > 60000 )); then
		echo "Total curl time - $(($CUTIME/60000)) min. $(($CUTIME%60000/1000)) sec. $(($CUTIME%1000)) ms."
	elif (( $CUTIME > 1000 )); then
		echo "Total curl time - $(($CUTIME/1000)) sec. $(($CUTIME%1000)) ms."
	else
		echo "Total curl time - $CUTIME ms."
	fi
	if (( $AVG > 60000 )); then
		echo "Average curl time - $(($AVG/60000)) min. $(($AVG%60000/1000)) sec. $(($AVG%1000)) ms."
	elif (( $AVG > 1000 )); then
		echo "Average curl time - $(($AVG/1000)) sec. $(($AVG%1000)) ms."
	else
		echo "Average curl time - $AVG ms."
	fi
	if (( $TTIME > 60000 )); then
		echo "Total time - $(($TTIME/60000)) min. $(($TTIME%60000/1000)) sec. $(($TTIME%1000)) ms."
	elif (( $TTIME > 1000 )); then
		echo "Total time - $(($TTIME/1000)) sec. $(($TTIME%1000)) ms."
	else
		echo "Total time - $TTIME ms."
	fi
else
	echo okay...
fi